cc_library(
    name = "pool",
    srcs = [
        "pool.cpp",
    ],
    hdrs = [
        "pool.hpp",
    ],
    deps = [],
    visibility = [
        "//visibility:public",
    ],
    linkopts = ["-pthread"],
)
