cc_library(
    name = "map",
    srcs = [],
    hdrs = [
        "map.hpp",
    ],
    deps = [
        "//src/io:io",
        "//src/thread:pool",
    ],
    visibility = [
        "//src:__pkg__",
    ],
)

cc_library(
    name = "reduce",
    srcs = [],
    hdrs = [
        "reduce.hpp",
    ],
    deps = [
        "//src/io:io",
        "//src/thread:pool",
    ],
    visibility = [
        "//src:__pkg__",
    ],
)